# Generated by Django 4.2.9 on 2024-02-14 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0004_movie_year_of_release'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='director',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='movie', to='movie_app.director', verbose_name='Director'),
        ),
        migrations.AlterField(
            model_name='review',
            name='stars',
            field=models.IntegerField(choices=[(1, '★ '), (2, '★ ★ '), (3, '★ ★ ★ '), (4, '★ ★ ★ ★ '), (5, '★ ★ ★ ★ ★ ')], default=5),
        ),
    ]
